### ISSUE TITLE
Sidebar gone

### ISSUE THREAD

**Issue by DashCat1243** [AntonioErdeljac/next13-discord-clone#24]
After I added the ModalProvider tag above {children} in the main layout.tsx the sidebar had disappeared completely. I tried taking the code directly from github for many files, but is it nowhere to be seen even after countless reloads and npm run dev's.

**Comment by Dharunprakash** [comment]
yeah same, have you found fix?

**Comment by Scrolls-of-the-nebulaic-whispers** [comment]
Same problem here

**Comment by Scrolls-of-the-nebulaic-whispers** [comment]
The fix is to use the same versions of dependencies as Antionio did. So simply copy dependencies from `package.json` to your's and `npm i` to install them. Worked for me.

**Comment by DashCat1243** [comment]
Thanks @Scrolls-of-the-nebulaic-whispers! Now I can finally go back to coding! 😁
