### ISSUE TITLE
credit card is needed in planetscale

### ISSUE THREAD

**Issue by 1933874502** [AntonioErdeljac/next13-discord-clone#6]
It seems a credit card is needed for create free database in planetscale.As a foreign student，I don‘t have a credit card，would someone help me invite me to thier organization so I can create a free database.It will be very helpful.

**Comment by manav-ayat** [comment]
https://medium.com/mastering-full-stack-development-with-next-js-and/building-a-real-time-messaging-app-a-step-by-step-tutorial-discord-clone-494aaef2fbb2


look at this article that i wrote for this.
would be gald for some clap reaction thank you

**Comment by manav-ayat** [comment]
also close the issue if it is solved for you

**Comment by 1933874502** [comment]
@manav-ayat sorry to bother you again.Have you deployed this project through Vercel? I want to access it online, but the demo provided by Antonio the user limit have been reached, and I am unable to access it

**Comment by manavkhadka0** [comment]
Since this uses socket io and vercel is serverless and it doesnt support it

**Comment by 1933874502** [comment]
or have you deploy it on railway for a demo?
&nbsp;


桃花仙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Manav ***@***.***&gt;; 
发送时间: 2023年9月3日(星期天) 下午3:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AntonioErdeljac/next13-discord-clone] credit card is needed in planetscale (Issue #6)





 
Since this uses socket io and vercel is serverless and it doesnt support it

**Comment by 1933874502** [comment]
@manavkhadka0 I followed your step，download docker desktop ect. But when I upload a server image，I got this error：Error: Invalid src prop [(https://utfs.io/f/02225339-0c16-46ce-afd8-2599ec503873_test.jpg)](http://localhost:3000/(https://utfs.io/f/02225339-0c16-46ce-afd8-2599ec503873_test.jpg)) on next/image, hostname "utfs.io" is not configured under images in your next.config.js，but image is indeed uploaded.

**Comment by manavkhadka0** [comment]
you need to add it the domian to next.config.js

**Comment by manavkhadka0** [comment]
```/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    config.externals.push({
      "utf-8-validate": "commonjs utf-8-validate",
      bufferutil: "commonjs bufferutil"
    });

    return config;
  },
  images: {
    domains: [
      "uploadthing.com",
      "utfs.io"
    ]
  }
}

module.exports = nextConfig`

**Comment by 1933874502** [comment]
@manavkhadka0 thanks a lot
